### ISSUE TITLE
Why max for correct answer?

### ISSUE THREAD

**Issue by Thecakeisr3al** [Unbrick/QuizduellXposed#2]
Isn't it possible to use something like "(correct)" instead of "maxmax", or even a tick (✔).
And add a space after the right answer.
Also in the correct box it says maxmax because it is called twice.

German Quizduell App

**Comment by Unbrick** [comment]
I'll check it this afternoon. But same for me, somehow it now gets called twice. And I'm thinking about to append a custom userdefined text.

**Comment by Thecakeisr3al** [comment]
I would hardcode that keep the module as small as possible.
A GUI is not really necessary.
Keep it clean sir =)
Also why do have have to hook two classes?
Sorry for the question i am not into xposed coding

**Comment by q-arizmatik** [comment]
I did not understand where I should use "max".

**Comment by Unbrick** [comment]
@DarioRugani 
I'll try to do it with a tick behind the correct answer. 

I need to hook twice because android is splitting big applications into two classes.dex. As i dont know in which of this classes.dex the method is (which differs in different quizduell versions), i need to hook both  classes.dex and try to find and hook the method.

@q-arizmatik 
I honestly dont really get your question. Things you need to do to get it to work:
1. Install any version of quizduell
2. Install QuizduellXposed
3. Soft-reboot your device
4. Behind the correct answer should be a "max" appended. Somehow it is now a "maxmax" due to a duplicate method call issued by quizduell. I'll try to fix this.

**Comment by Unbrick** [comment]
@DarioRugani 
Fixed now the double calling of the method bug and now appening a "✓"
Updated version on Xposed, should be fine now. If you experience any bugs, let me know!

**Comment by Thecakeisr3al** [comment]
Works great
