### ISSUE TITLE
Can you explain one moment

### ISSUE THREAD

**Issue by Radzhab** [Unbrick/QuizduellXposed#9]
I cannot understand what make this code. 
```
 Object alternativeTextView = getObjectField(correctButton, "alternativeTextView");
                if (!(
                        callMethod(alternativeTextView, "getText") instanceof SpannableStringBuilder
                                ? (String) callMethod(callMethod(alternativeTextView, "getText"), "toString")
                                : (String) callMethod(alternativeTextView, "getText")).contains("✓")) {
                    callMethod(alternativeTextView, "append", " ✓");
                    Log.d(TAG, "Solution appended");
                }

**Comment by Unbrick** [comment]
`Object alternativeTextView = getObjectField(correctButton, "alternativeTextView");`

This line gets the TextView object from the "correct button" object. The way I'm doing it is called reflection because I don't have any direct access to the object I need. Without reflection it would look like:
`TextView alternativeTextView = correctButton.alternativeTextView;`



`if (!(
                        callMethod(alternativeTextView, "getText") instanceof SpannableStringBuilder
                                ? (String) callMethod(callMethod(alternativeTextView, "getText"), "toString")
                                : (String) callMethod(alternativeTextView, "getText")).contains("✓"))`

This line checks whether the text of the text view is a SpannableStringBuilder or just a simple string. This was needed because sometimes the text was a SpannableStringBuilder, sometimes just a String. Then I'm checking if the tick is already appended to the string to avoid double appending the tick. Depending on the previous if-statement result it's appending a tick. Without reflection it would be something like:
`if(!(alternativeTextView.getText() instanceof SpannableStringBuilder ? alternativeTextView.getText().toString() : alternativeTextView.getText()).contains("✓")`


Here is inside the if-statement a simplified if statement which works as follows:
`methodcallWhichReturnsABoolan/booleanObject ? resultIfTrue : resultIfFalse`



You might be able to understand it better when you decompile Quizduell and look at the Objects and Fields, I'd recommend JaDx as a decompiler!

**Comment by Radzhab** [comment]
THX!!!
